version: '2'

services:
  nginx-proxy:
    image: mongo-express
    expose:
      - "8081"
    networks:
      - www_home
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - VIRTUAL_HOST=mongo.local, mongo.dryg.io
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  www_home:
